# .github/workflows/docs.yml
name: Build Docs

on:
  pull_request:
    branches:
      - master
    paths:
      - 'man/**'
      - '**.md'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository }}/docs-builder:latest

    steps:
      - uses: actions/checkout@v5

      - name: Build docs
        run: make doc-regenerate
