# .github/workflows/docs.yml
name: Build Docs

on:
  pull_request:
    branches:
      - master
    paths:
      - 'man/**'
      - '**.md'
      - '.github/docs-image/**'

jobs:
  compute-image-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v5
      - id: set-tag
        run: |
          echo "tag=${{ hashFiles('.github/docs-image/**') }}" >> $GITHUB_OUTPUT

  build-docs:
    runs-on: ubuntu-latest
    needs: compute-image-tag
    container:
      image: ghcr.io/${{ github.repository }}/docs-builder:${{ needs.compute-image-tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v5

      - name: Build docs
        run: make doc-regenerate
